### ISSUE TITLE
constantly auth failure after 14-hour running

### ISSUE THREAD

**Issue by yw662** [cilynx/rtl88x2BU_WiFi_linux_v5.2.4.1_22719_COEX20170518-4444.20170613#1]
It can be solved by a reboot, and I forget to store the dmesg.

and maybe it is network related.

**Comment by yw662** [comment]
This issue can be solved by remove and plug the wireless card.

**Comment by cilynx** [comment]
Try doing a pull now and trying again.  I just pushed some cleanup around compiler warnings that I wrote a few weeks back.

If it's still giving you issues, any logs you can share would be helpful.

**Comment by cilynx** [comment]
Closing due to lack of response.  Feel free to reopen if you can provide additional details to be used for troubleshooting.
