### ISSUE TITLE
Wouldn't you like to update the driver?

### ISSUE THREAD

**Issue by mkolender** [cilynx/rtl88x2BU_WiFi_linux_v5.2.4.1_22719_COEX20170518-4444.20170613#6]
Not so long ago I bought a Wi-Fi card with rtl8811CU chipset, but the CD I recieved with it also had a newer version of rtl88x2BU driver. I don't have this card, but I thought it might be useful for someone so I've extracted it and pushed to github. Maybe you could update your driver to this version? You can find the extracted driver here:
[https://github.com/whitebatman2/rtl88x2BU](https://github.com/whitebatman2/rtl88x2BU)

**Comment by cilynx** [comment]
Interesting -- I haven't seen v5.2.4.4 anywhere in the wild yet.  Which Wi-Fi card did this come with?  Can you by chance image the ISO and drop it somewhere I can pull it down?  These driver CDs occasionally have interesting documentation and support material.  Thanks!

**Comment by cilynx** [comment]
Never mind wrapping up the ISO -- I found a copy [on Dropbox](https://www.dropbox.com/s/b3muqkezsdirmje/Agedate-AC1200-New%20Driver%203.22-LINUX.zip) linked by the seller on [an Amazon listing](https://amzn.to/2Js9AL2).  Don't you love how reputable these driver bundles are?  Nothing say "no one tampered with this after it left the OEM" like downloading from Dropbox / Baidu / etc.

**Comment by mkolender** [comment]
This driver came with this card:
https://aliexpress.com/item/iMice-USB-WiFi-Adapter-PC-600Mbps-AC-Mini-Wireless-Wifi-Antenna-Network-Card-Dual-Band-2/32818267925.html
This seller says the chipset is rtl8811. Maybe he sends randomly rtl8811AU and rtl8811CU :laughing:. I bought this card, because I thought it has rtl8821AU chip and there were already working drivers for it. It was actually rtl8821CU. I had to patch the driver from CD to work on newer linux kernels.

**Comment by cilynx** [comment]
Right on -- thank you.  I've created a new repo for [v5.2.4.4_25643.20171212_COEX20171012-5044](https://github.com/cilynx/rtl88x2BU_WiFi_linux_v5.2.4.4_25643.20171212_COEX20171012-5044) and also dropped Realtek a note to see if they could send me their official release source so I can be more sure of its provenance.
